[database]
name = "dbname"
user = "user"
password = "password"
host = "db host"

[lark]
path = "bot path"

[juzihudong]
endpoint = "api"
token = "token"

[keyword]
sync_timer = 5

[alive]
tick = 10
limit = 3

[lark_bot]
app_id = "app_id"
app_secret = "app_secret"
endpoint = "end_point"
token = "token"

[lark_picture_room]
chat_id = "chat_id"

[lark_text_room]
chat_id = "chat_id"

[whitelist]
room_id = "room_id"
