[database]
name = "dbname"
user = "user"
password = "password"
host = "db host"

[lark]
path = "bot path"

[juzihudong]
endpoint = "api"
token = "token"

[keyword]
sync_timer = 5

[alive]
tick = 10
limit = 3
